### ISSUE TITLE
How can I load 'rnn', 'cbp', and 'torchx'?

### ISSUE THREAD

**Issue by kylemin** [ruotianluo/refexp-comprehension#1]
If I try to require 'rnn', 'cbp', and 'torchx', it says it cannot find rnn or cbp or torchx as below.
` module 'rnn' not found:No LuaRocks module found for rnn `

Also, if I just comment them out, another error occurs.
` attempt to index field 'FastLSTM' (a nil value)`

**Comment by ruotianluo** [comment]
Did you install these. (for cbp, I think you need to install from source.)

**Comment by kylemin** [comment]
Thanks!
